import type { CanvasNode, ComposerPreset, NodeType } from "./canvas-types";

export const COMPOSER_PRESETS: Record<NodeType, ComposerPreset> = {
	text: {
		model: "GPT-5.5 ☁️",
		variants: "1x",
		credits: "",
		placeholder: "描述你想生成的文本内容",
		meta: [],
		prompt: "",
		textMode: "standard",
	},
	shot: {
		model: "",
		variants: "1x",
		credits: "",
		placeholder: "描述镜头意图、景别、构图、角色位置和运镜节奏",
		meta: ["镜头", "构图", "预演"],
		prompt: "",
		shotSize: "远景",
		cameraAngle: "平视",
		frameRatio: "16:9",
	},
	character: {
		model: "",
		variants: "1x",
		credits: "",
		placeholder: "描述角色身份、外观、服装、动作与情绪",
		meta: ["角色", "身份", "动作"],
		prompt: "",
	},
	scene: {
		model: "",
		variants: "1x",
		credits: "",
		placeholder: "描述场景空间、时间氛围、光线与环境细节",
		meta: ["场景", "氛围", "空间"],
		prompt: "",
	},
	image: {
		model: "Nano Banana ☁️",
		variants: "1x",
		credits: "￥",
		placeholder: "描述你想生成的图片内容",
		meta: ["Nano Banana", "标准", "1K"],
		prompt: "",
		version: "标准",
		aspectRatio: "1:1",
		resolution: "1K",
		outputFormat: "png",
		quality: "auto",
		background: "auto",
		watermark: "false",
		promptExtend: "true",
	},
	video: {
		model: "VEO 3.1 ☁️",
		variants: "1x",
		credits: "￥",
		placeholder: "描述你想生成的视频内容",
		meta: ["VEO 3.1", "16:9", "1K", "8s"],
		prompt: "",
		videoGenerationMode: "text",
		videoQuality: "标准",
		aspectRatio: "16:9",
		resolution: "1K",
		duration: "8s",
	},
	audio: {
		model: "MiniMax Speech 2.8 HD ☁️",
		variants: "",
		credits: "",
		placeholder: "输入要合成的文本或音频处理需求",
		meta: ["MiniMax", "Speech 2.8 HD", "TTS"],
		prompt: "",
		audioVoiceMode: "tts",
		audioVoiceName: "",
		audioVoiceId: "",
		audioVoiceStyle: "",
	},
	music: {
		model: "Suno ☁️",
		variants: "",
		credits: "￥",
		placeholder: "描述你想要的歌曲、风格、情绪或歌词方向",
		meta: ["Suno", "作曲"],
		prompt: "",
		musicAction: "music",
		musicStyleCategory: "pop",
		musicStylePreset: "anthemic-pop",
	},
	editor: {
		model: "Nano Banana ☁️",
		variants: "",
		credits: "￥",
		placeholder: "描述编辑意图，或打开编辑器继续处理",
		meta: ["Nano Banana", "编辑"],
		prompt: "",
		version: "标准",
		aspectRatio: "1:1",
		resolution: "1K",
		outputFormat: "png",
		quality: "auto",
		background: "auto",
		watermark: "false",
		promptExtend: "true",
	},
};

export const INITIAL_NODES: CanvasNode[] = [
	{
		id: "node-text-1",
		type: "text",
		x: 420,
		y: 300,
		width: 328,
		height: 328,
		title: "文本",
		composer: { ...COMPOSER_PRESETS.text },
	},
];
