// Shared type definitions used across multiple Studio pages.
// Extracted from chat/types.ts, group-chat/types.ts, and Characters.tsx
// to eliminate duplicate type definitions (OPT-C2).

import type { VideoGenConfig, CharacterVoice } from "@tavernos/core";

// --- Persona / Character types ---

// Re-export CharacterVoice so existing imports from "shared/types" keep working.
// The canonical definition lives in @tavernos/core (CharacterVoiceSchema with
// Zod validation); the local duplicate was removed to avoid drift (M13).
export type { CharacterVoice };

/** Data payload of a persona card — superset of all page-specific variants. */
export interface PersonaData {
  name: string;
  description?: string;
  personality?: string;
  scenario?: string;
  first_mes?: string;
  /** TavernOS extensions including per-character voice config. */
  extensions?: {
    tavernos?: {
      voice?: CharacterVoice;
      /** Avatar image URL (e.g. a WebDAV direct link for Plus-generated characters). */
      avatar?: string;
      /** True if auto-generated by the Plus module (routes to global WebDAV library). */
      plusGenerated?: boolean;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
}

/** A persona card loaded from disk (filename + data). */
export interface PersonaCard {
  filename: string;
  data: PersonaData;
}

/** API response shape for listing persona cards. */
export interface CharactersResponse {
  characters: PersonaCard[];
}

// --- LLM token usage ---

/** Token usage statistics returned by the LLM API. */
export interface TokenUsage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
}

// --- SSE event types (common across streaming endpoints) ---

/** SSE delta event — a chunk of streaming content. */
export interface SSEDeltaEvent {
  type: "delta";
  content: string;
}

/** SSE error event — signals a stream error. */
export interface SSEErrorEvent {
  type: "error";
  error: string;
}

// --- Generic API response types ---

/** Generic delete response returned by DELETE endpoints. */
export interface DeleteResponse {
  success: boolean;
}

// --- Background task types (shared between server task-manager and frontend store) ---

export type TaskType =
  | "create-chat"
  | "create-autopilot"
  | "chat-stream"
  | "generate-three-view"
  | "generate-mj-avatar"
  | "generate-cover"
  | "deepgame-turn"
  | "deepgame-score"
  | "deepgame-world";

export type TaskStatus = "pending" | "running" | "completed" | "failed" | "cancelled";

export interface AgentProgressItem {
  stage: string;
  issues?: number;
  fixes?: number;
}

export interface TaskProgress {
  current: number;
  total: number;
  message?: string;
  agentStage?: string;
  agentCompleted?: AgentProgressItem[];
}

export interface Task {
  id: string;
  type: TaskType;
  label: string;
  status: TaskStatus;
  progress: TaskProgress;
  result?: unknown;
  error?: string;
  projectId?: string;
  meta?: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
}

// --- Video clip types (shared between server video-types and frontend video page) ---

/** A single issue flagged during clip review. */
export interface ReviewIssue {
  severity: "critical" | "major" | "minor";
  dimension: string;
  description: string;
  fixInstruction?: string;
}

/** Persisted review result attached to a saved clip. */
export interface SavedClipReview {
  verdict: string;
  score: number;
  grade?: string;
  issues: ReviewIssue[];
  postFixSuggestion?: string;
  rerollPrompt?: string;
  summary?: string;
  /** Legacy field — older reviews stored plain-string suggestions. */
  suggestions?: string[];
  /** ISO timestamp of the last review. */
  reviewedAt?: string;
}

/** Saved clip record (persisted to disk as JSON). */
export interface SavedClip {
  id: string;
  chapterId: number;
  clipNumber: number;
  prompt: string;
  videoUrl: string;
  thumbnailUrl?: string;
  duration: number;
  status: string;
  generateConfig: VideoGenConfig;
  createdAt: string;
  /** Sort order for manual reordering (lower = earlier). Defaults to createdAt order. */
  dragIndex?: number;
  /** Last review result (persisted so it survives page refresh). */
  lastReview?: SavedClipReview;
}
