// Deterministic LLM stub for testing
// Activated when TAVERNOS_LLM_STUB=true environment variable is set

import type { LLMMessage, LLMResponse, ChatOptions } from "./types.js";

const STUB_ENV_VAR = "TAVERNOS_LLM_STUB";

export function isLlmStubEnabled(): boolean {
  return process.env[STUB_ENV_VAR] === "true" ||
    process.env[STUB_ENV_VAR] === "1";
}

/**
 * Generate a deterministic response based on the input messages.
 * This does NOT call any API — it produces predictable output for testing.
 */
export function stubChatCompletion(
  messages: ReadonlyArray<LLMMessage>,
  _options?: ChatOptions,
): LLMResponse {
  const lastUserMsg = [...messages].reverse().find((m) => m.role === "user");
  const systemMsg = messages.find((m) => m.role === "system");

  // Deterministic: hash the input to produce a stable response
  const inputHash = simpleHash(
    (systemMsg?.content ?? "") + "|" + (lastUserMsg?.content ?? ""),
  );

  const content = buildStubResponse(lastUserMsg?.content ?? "", inputHash);

  // Simulate token usage
  const promptTokens = messages.reduce(
    (sum, m) => sum + Math.ceil(m.content.length / 4),
    0,
  );
  const completionTokens = Math.ceil(content.length / 4);

  return {
    content,
    usage: {
      promptTokens,
      completionTokens,
      totalTokens: promptTokens + completionTokens,
    },
  };
}

function buildStubResponse(userContent: string, hash: number): string {
  const topic = userContent.slice(0, 80);

  return [
    `[STUB RESPONSE #${hash}]`,
    ``,
    `This is a deterministic stub response generated by TavernOS LLM stub.`,
    `The stub was activated because TAVERNOS_LLM_STUB=true.`,
    ``,
    `Input topic: ${topic}...`,
    ``,
    `In production, this would be replaced by a real LLM API call.`,
    `The stub ensures tests are reproducible without API keys or network access.`,
  ].join("\n");
}

function simpleHash(str: string): number {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = (hash << 5) - hash + char;
    hash |= 0;
  }
  return Math.abs(hash);
}
